name: krivisha_app
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.1.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  table_calendar: ^3.1.2
  autocomplete_textfield: ^2.0.1
  url_launcher: ^6.3.0
  # flutter_typeahead: ^4.8.0
  flutter_svg: ^2.0.9
  shimmer: ^3.0.0
  http: ^0.13.6
  shared_preferences: ^2.2.3
  flutter_spinkit: ^5.2.1
  skeleton_text: ^3.0.1
  file_picker: ^8.0.6
  network_image: ^0.1.1
  get: ^4.6.6
  webview_flutter: ^4.10.0
  flutter_background_service_android: ^6.2.3
  provider: ^6.1.2
  intl: ^0.19.0
  dropdown_button2: ^2.3.9
  permission_handler: ^11.3.1
  firebase_core: ^3.4.0
  firebase_messaging: ^15.0.4
  flutter_local_notifications: ^18.0.1
  cloud_firestore: ^5.4.0
  firebase_crashlytics: ^4.1.5
  device_info_plus: ^11.1.1
  pinput: ^5.0.1
  flutter_searchable_dropdown: ^2.0.0
  lottie: ^3.0.0
  google_fonts: ^4.0.4
  photo_view: ^0.15.0
  dropdown_search: ^5.0.6
  animate_do: ^4.2.0
  another_flushbar: ^1.12.30
  flutter_launcher_icons: ^0.14.3
  firebase_analytics: ^11.4.6


flutter:
  uses-material-design: true
  assets:
    - images/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/applogo.jpg"
  min_sdk_android: 21 # Optional: Minimum Android SDK version
  # adaptive_icon_foreground: "assets/icon/foreground.png" # Optional for Android adaptive icons
  # adaptive_icon_background: "#FFFFFF" # Optional: Background color or image path