// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAt5MCVT5YNERVNAoBQ4D_ILQWTtsZVY70',
    appId: '1:701776477236:web:6541a0ddd0316865509e61',
    messagingSenderId: '701776477236',
    projectId: 'krivishaapp',
    authDomain: 'krivishaapp.firebaseapp.com',
    storageBucket: 'krivishaapp.firebasestorage.app',
    measurementId: 'G-RB6G9LBHWN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD888pkt2orUuYBMP0btpEkA6siAK7Lch0',
    appId: '1:701776477236:android:51486a434e24f58d509e61',
    messagingSenderId: '701776477236',
    projectId: 'krivishaapp',
    storageBucket: 'krivishaapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3UErItO68N_Xh31oNoDOKWP2DzQO4uwo',
    appId: '1:701776477236:ios:967b70d978ab663c509e61',
    messagingSenderId: '701776477236',
    projectId: 'krivishaapp',
    storageBucket: 'krivishaapp.firebasestorage.app',
    iosBundleId: 'com.example.quickenlancerApk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3UErItO68N_Xh31oNoDOKWP2DzQO4uwo',
    appId: '1:701776477236:ios:967b70d978ab663c509e61',
    messagingSenderId: '701776477236',
    projectId: 'krivishaapp',
    storageBucket: 'krivishaapp.firebasestorage.app',
    iosBundleId: 'com.example.quickenlancerApk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAt5MCVT5YNERVNAoBQ4D_ILQWTtsZVY70',
    appId: '1:701776477236:web:f7c851ed9666b2c2509e61',
    messagingSenderId: '701776477236',
    projectId: 'krivishaapp',
    authDomain: 'krivishaapp.firebaseapp.com',
    storageBucket: 'krivishaapp.firebasestorage.app',
    measurementId: 'G-6CHZL212TF',
  );

}